"""Read-only health checks for a local Agent Hub checkout."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import importlib.util
import json
import os
from pathlib import Path
import shutil
import sys
from typing import Any, Callable, Dict, Sequence

from agent_hub import local_setup

PACKAGE_NAMES = (
    "agent_hub",
    "orchestrate_codex",
    "claude_codex",
    "grok_codex",
    "google_antigravity_codex",
    "openai_codex",
)


@dataclass(frozen=True)
class DoctorCheck:
    id: str
    status: str
    message: str
    details: Dict[str, Any] | None = None

    def public(self) -> Dict[str, Any]:
        value = {
            "id": self.id,
            "status": self.status,
            "message": self.message,
        }
        if self.details:
            value["details"] = dict(self.details)
        return value


def _normalized_rules(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    marker = "<!-- Generated by Ruler -->"
    if text.startswith(marker):
        text = text[len(marker) :]
    return text.lstrip("\n")


def _rules_check(repo_root: Path) -> DoctorCheck:
    agents = _normalized_rules(repo_root / "AGENTS.md")
    claude = _normalized_rules(repo_root / "CLAUDE.md")
    if agents is None or claude is None:
        return DoctorCheck(
            "rules",
            "fail",
            "AGENTS.md and CLAUDE.md must both exist and be valid UTF-8.",
        )
    if agents != claude:
        return DoctorCheck(
            "rules",
            "fail",
            "AGENTS.md and CLAUDE.md differ; run scripts/sync.sh.",
        )
    return DoctorCheck("rules", "pass", "Generated instruction files agree.")


def _package_check(
    find_spec: Callable[[str], Any],
) -> DoctorCheck:
    missing = []
    for name in PACKAGE_NAMES:
        try:
            found = find_spec(name)
        except (ImportError, AttributeError, ValueError):
            found = None
        if found is None:
            missing.append(name)
    if missing:
        return DoctorCheck(
            "packages",
            "fail",
            "One or more Agent Hub packages are unavailable.",
            {"missing": missing},
        )
    return DoctorCheck(
        "packages",
        "pass",
        f"All {len(PACKAGE_NAMES)} Agent Hub packages are importable.",
    )


def _configured_hub_command(repo_root: Path) -> Path | None:
    try:
        payload = json.loads((repo_root / ".mcp.json").read_text(encoding="utf-8"))
        value = payload["mcpServers"]["agent-hub"]["command"]
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError):
        return None
    path = Path(str(value)).expanduser()
    return path if path.is_absolute() else None


def _local_config_check(repo_root: Path) -> DoctorCheck:
    configured = _configured_hub_command(repo_root)
    try:
        plan = local_setup.plan_setup(repo_root, hub_command=configured)
    except local_setup.SetupError as exc:
        return DoctorCheck("local_config", "fail", str(exc))
    if plan.changed:
        return DoctorCheck(
            "local_config",
            "fail",
            "Machine-local MCP config is missing or stale; prepare and apply `agent-hub setup`.",
            {"changed": [item.relative_path for item in plan.changed]},
        )
    return DoctorCheck(
        "local_config",
        "pass",
        "Machine-local MCP config consistently references an executable bridge.",
        {"bridge": str(configured)} if configured is not None else None,
    )


def _hub_executable_check(repo_root: Path) -> DoctorCheck:
    executable = _configured_hub_command(repo_root) or (
        repo_root / ".venv" / "bin" / "agent-hub-mcp"
    )
    if executable.is_file() and not executable.is_symlink() and os.access(executable, os.X_OK):
        return DoctorCheck(
            "agent_hub_mcp",
            "pass",
            "agent-hub-mcp console script is executable.",
            {"path": str(executable)},
        )
    return DoctorCheck(
        "agent_hub_mcp",
        "fail",
        "agent-hub-mcp is missing; create the project venv and install this checkout.",
    )


def _command_check(
    name: str,
    *,
    which: Callable[[str], str | None],
    required: bool,
    message: str,
) -> DoctorCheck:
    resolved = which(name)
    if resolved:
        return DoctorCheck(
            f"command_{name}",
            "pass",
            f"{name} is available.",
            {"path": resolved},
        )
    return DoctorCheck(
        f"command_{name}",
        "fail" if required else "warn",
        message,
    )


def _default_live_status() -> Dict[str, Any]:
    from openai_codex.auth import status

    return status(refresh=False, timeout=5.0)


def _live_gpt_check(
    live_status: Callable[[], Dict[str, Any]],
) -> DoctorCheck:
    try:
        current = live_status()
    except Exception as exc:  # noqa: BLE001
        return DoctorCheck(
            "gpt_live",
            "warn",
            f"Codex account status could not be read: {type(exc).__name__}.",
        )
    safe = {
        key: current.get(key)
        for key in (
            "installed",
            "configured",
            "logged_in",
            "subscription_login",
            "auth_mode",
            "plan_type",
            "warning",
        )
    }
    if current.get("subscription_login"):
        return DoctorCheck(
            "gpt_live",
            "pass",
            "The GPT provider can use the official Codex subscription login.",
            safe,
        )
    return DoctorCheck(
        "gpt_live",
        "warn",
        "Codex is not currently using a supported ChatGPT subscription login.",
        safe,
    )


def run_doctor(
    repo_root: str | os.PathLike[str],
    *,
    strict: bool = False,
    live: bool = False,
    which: Callable[[str], str | None] = shutil.which,
    find_spec: Callable[[str], Any] = importlib.util.find_spec,
    live_status: Callable[[], Dict[str, Any]] = _default_live_status,
) -> Dict[str, Any]:
    try:
        root = Path(repo_root).expanduser().resolve(strict=True)
    except OSError as exc:
        return {
            "schema": "agent_hub_doctor_v1",
            "success": False,
            "strict": strict,
            "live": live,
            "checks": [
                DoctorCheck(
                    "repo_root",
                    "fail",
                    f"Repository root does not exist: {exc}",
                ).public()
            ],
            "summary": {"pass": 0, "warn": 0, "fail": 1},
        }
    checks = [
        DoctorCheck(
            "python",
            "pass" if sys.version_info >= (3, 10) else "fail",
            (
                f"Python {sys.version_info.major}.{sys.version_info.minor} is active."
                if sys.version_info >= (3, 10)
                else "Python 3.10 or newer is required."
            ),
        ),
        _rules_check(root),
        _package_check(find_spec),
        _local_config_check(root),
        _hub_executable_check(root),
        _command_check(
            "codex",
            which=which,
            required=False,
            message="codex is unavailable; the GPT provider will remain offline.",
        ),
    ]
    if live:
        checks.append(_live_gpt_check(live_status))
    counts = {
        status: sum(1 for item in checks if item.status == status)
        for status in ("pass", "warn", "fail")
    }
    success = counts["fail"] == 0 and not (strict and counts["warn"])
    return {
        "schema": "agent_hub_doctor_v1",
        "success": success,
        "strict": strict,
        "live": live,
        "checks": [item.public() for item in checks],
        "summary": counts,
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run read-only Agent Hub health checks. Provider subprocesses are "
            "used only with --live."
        )
    )
    parser.add_argument(
        "--repo-root",
        default=str(Path(__file__).resolve().parents[2]),
    )
    parser.add_argument("--json", action="store_true")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat warnings as a failing result.",
    )
    parser.add_argument(
        "--live",
        action="store_true",
        help="Read redacted Codex account status without refreshing or generating.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    result = run_doctor(
        args.repo_root,
        strict=args.strict,
        live=args.live,
    )
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        for item in result["checks"]:
            print(f"{item['status'].upper():4} {item['id']}: {item['message']}")
        summary = result["summary"]
        print(f"doctor: {summary['pass']} pass, {summary['warn']} warn, {summary['fail']} fail")
    return 0 if result["success"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
