from __future__ import annotations

import json

from agent_hub import doctor, local_setup


def _healthy_repo(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    rules = "<!-- Generated by Ruler -->\n\n# Rules\n\n- Keep evidence.\n"
    (root / "AGENTS.md").write_text(rules, encoding="utf-8")
    (root / "CLAUDE.md").write_text(rules, encoding="utf-8")
    executable = root / ".venv" / "bin" / "agent-hub-mcp"
    executable.parent.mkdir(parents=True)
    executable.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    executable.chmod(0o755)
    notes = root / "memory" / "data"
    notes.mkdir(parents=True)
    (notes / "decision.md").write_text("# Decision\n", encoding="utf-8")
    local_setup.apply_plan(local_setup.plan_setup(root))
    return root


def _which(name):
    return f"/tools/{name}"


def _find_spec(_name):
    return object()


def test_doctor_healthy_path_is_read_only_and_does_not_call_live_status(
    tmp_path,
):
    root = _healthy_repo(tmp_path)
    before = {
        path: (root / path).stat().st_mtime_ns
        for path in local_setup.CONFIG_PATHS
    }

    def forbidden_live():
        raise AssertionError("default doctor must not start provider subprocesses")

    result = doctor.run_doctor(
        root,
        which=_which,
        find_spec=_find_spec,
        live_status=forbidden_live,
    )

    assert result["success"] is True
    assert result["summary"] == {"pass": 8, "warn": 0, "fail": 0}
    assert all(item["id"] != "gpt_live" for item in result["checks"])
    after = {
        path: (root / path).stat().st_mtime_ns
        for path in local_setup.CONFIG_PATHS
    }
    assert after == before


def test_optional_commands_warn_but_only_strict_mode_fails(tmp_path):
    root = _healthy_repo(tmp_path)

    def missing_optional(_name):
        return None

    normal = doctor.run_doctor(
        root,
        which=missing_optional,
        find_spec=_find_spec,
    )
    strict = doctor.run_doctor(
        root,
        strict=True,
        which=missing_optional,
        find_spec=_find_spec,
    )

    assert normal["success"] is True
    assert normal["summary"]["warn"] == 2
    assert strict["success"] is False
    assert strict["summary"]["fail"] == 0


def test_require_memory_and_config_drift_are_failures(tmp_path):
    root = _healthy_repo(tmp_path)
    (root / "memory" / "data" / "decision.md").unlink()
    root_config = root / ".mcp.json"
    parsed = json.loads(root_config.read_text(encoding="utf-8"))
    parsed["mcpServers"]["agent-hub"]["command"] = "/wrong/path"
    root_config.write_text(json.dumps(parsed), encoding="utf-8")

    result = doctor.run_doctor(
        root,
        require_memory=True,
        which=lambda name: None if name == "uvx" else f"/tools/{name}",
        find_spec=_find_spec,
    )

    by_id = {item["id"]: item for item in result["checks"]}
    assert result["success"] is False
    assert by_id["local_config"]["status"] == "fail"
    assert by_id["command_uvx"]["status"] == "fail"
    assert by_id["memory_notes"]["status"] == "fail"


def test_live_doctor_uses_redacted_non_refreshing_status_contract(tmp_path):
    root = _healthy_repo(tmp_path)
    calls = 0

    def live_status():
        nonlocal calls
        calls += 1
        return {
            "installed": True,
            "configured": True,
            "logged_in": True,
            "subscription_login": True,
            "auth_mode": "chatgpt",
            "plan_type": "pro",
            "email": "must-not-be-returned@example.com",
            "access_token": "must-not-be-returned",
        }

    result = doctor.run_doctor(
        root,
        live=True,
        which=_which,
        find_spec=_find_spec,
        live_status=live_status,
    )

    assert calls == 1
    assert result["success"] is True
    serialized = json.dumps(result)
    assert "must-not-be-returned" not in serialized
    assert "gpt_live" in serialized


def test_doctor_cli_json_exit_code(monkeypatch, capsys):
    monkeypatch.setattr(
        doctor,
        "run_doctor",
        lambda *_args, **_kwargs: {
            "schema": "agent_hub_doctor_v1",
            "success": False,
            "checks": [],
            "summary": {"pass": 0, "warn": 0, "fail": 1},
        },
    )

    assert doctor.main(["--repo-root", ".", "--json"]) == 1
    assert json.loads(capsys.readouterr().out)["success"] is False
