#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly SCRIPT_DIR
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
readonly REPO_ROOT
readonly GENERATED_FILES=(
  "AGENTS.md"
  "CLAUDE.md"
  ".gemini/settings.json"
)

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/agent-hub-sync.XXXXXX")"

cleanup() {
  rm -rf -- "${tmp_dir}"
}

trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

for file in "${GENERATED_FILES[@]}"; do
  snapshot_path="${tmp_dir}/before/${file}"
  mkdir -p -- "$(dirname -- "${snapshot_path}")"
  if [[ -f "${REPO_ROOT}/${file}" ]]; then
    cp -- "${REPO_ROOT}/${file}" "${snapshot_path}"
  else
    : > "${snapshot_path}.missing"
  fi
done

"${SCRIPT_DIR}/sync.sh"

sync_changed=0
for file in "${GENERATED_FILES[@]}"; do
  if [[ ! -f "${REPO_ROOT}/${file}" ]]; then
    echo "error: expected generated file is missing: ${file}" >&2
    exit 1
  fi
  if ! git -C "${REPO_ROOT}" ls-files --error-unmatch -- "${file}" >/dev/null 2>&1; then
    echo "error: generated file is not tracked by Git: ${file}" >&2
    exit 1
  fi

  snapshot_path="${tmp_dir}/before/${file}"
  if [[ -f "${snapshot_path}.missing" ]]; then
    echo "error: sync had to create missing generated file: ${file}" >&2
    sync_changed=1
  elif ! cmp -s "${snapshot_path}" "${REPO_ROOT}/${file}"; then
    echo "error: sync had to update stale generated file: ${file}" >&2
    diff -u "${snapshot_path}" "${REPO_ROOT}/${file}" || true
    sync_changed=1
  fi
done

if [[ "${sync_changed}" -ne 0 ]]; then
  echo "run ./scripts/check-sync.sh again after reviewing the regenerated files" >&2
  exit 1
fi

sed '1{/^<!-- Generated by Ruler -->$/d;}' \
  "${REPO_ROOT}/CLAUDE.md" > "${tmp_dir}/CLAUDE.md"
sed '1{/^<!-- Generated by Ruler -->$/d;}' \
  "${REPO_ROOT}/AGENTS.md" > "${tmp_dir}/AGENTS.md"

if ! cmp -s "${tmp_dir}/CLAUDE.md" "${tmp_dir}/AGENTS.md"; then
  echo "error: CLAUDE.md and AGENTS.md do not contain the same canonical rules" >&2
  diff -u "${tmp_dir}/CLAUDE.md" "${tmp_dir}/AGENTS.md" || true
  exit 1
fi

if [[ -e "${REPO_ROOT}/.ruler" || -L "${REPO_ROOT}/.ruler" ]]; then
  echo "error: temporary .ruler bridge was not cleaned up" >&2
  exit 1
fi

echo "Ruler sync check passed."
