#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly SCRIPT_DIR
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
readonly REPO_ROOT
readonly GENERATED_FILES=(
  "AGENTS.md"
  "CLAUDE.md"
)

fixture_root="$(mktemp -d "${TMPDIR:-/tmp}/agent-hub-sync-check.XXXXXX")"

cleanup() {
  rm -rf -- "${fixture_root}"
}

trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

mkdir -p -- \
  "${fixture_root}/instructions" \
  "${fixture_root}/scripts" \
  "${fixture_root}/src/agent_hub"
cp -R -- "${REPO_ROOT}/instructions/.ruler" "${fixture_root}/instructions/.ruler"
cp -- "${SCRIPT_DIR}/sync.sh" "${fixture_root}/scripts/sync.sh"
cp -- "${REPO_ROOT}/src/agent_hub/__init__.py" \
  "${fixture_root}/src/agent_hub/__init__.py"
cp -- "${REPO_ROOT}/src/agent_hub/local_setup.py" \
  "${fixture_root}/src/agent_hub/local_setup.py"
chmod +x "${fixture_root}/scripts/sync.sh"

# Generate only inside the disposable tree. This keeps check-sync read-only with
# respect to the real checkout, even when tracked generated files are stale.
"${fixture_root}/scripts/sync.sh" >/dev/null

sync_changed=0
for file in "${GENERATED_FILES[@]}"; do
  if [[ ! -f "${REPO_ROOT}/${file}" ]]; then
    echo "error: expected generated file is missing: ${file}" >&2
    sync_changed=1
    continue
  fi
  if ! git -C "${REPO_ROOT}" ls-files --error-unmatch -- "${file}" >/dev/null 2>&1; then
    echo "error: generated file is not tracked by Git: ${file}" >&2
    sync_changed=1
    continue
  fi
  if ! cmp -s "${fixture_root}/${file}" "${REPO_ROOT}/${file}"; then
    echo "error: generated file is stale: ${file}" >&2
    diff -u "${REPO_ROOT}/${file}" "${fixture_root}/${file}" || true
    sync_changed=1
  fi
done

if [[ "${sync_changed}" -ne 0 ]]; then
  echo "run ./scripts/sync.sh and review the regenerated files" >&2
  exit 1
fi

sed '1{/^<!-- Generated by Ruler -->$/d;}' \
  "${REPO_ROOT}/CLAUDE.md" > "${fixture_root}/CLAUDE.normalized.md"
sed '1{/^<!-- Generated by Ruler -->$/d;}' \
  "${REPO_ROOT}/AGENTS.md" > "${fixture_root}/AGENTS.normalized.md"

if ! cmp -s \
  "${fixture_root}/CLAUDE.normalized.md" \
  "${fixture_root}/AGENTS.normalized.md"; then
  echo "error: CLAUDE.md and AGENTS.md do not contain the same canonical rules" >&2
  diff -u \
    "${fixture_root}/CLAUDE.normalized.md" \
    "${fixture_root}/AGENTS.normalized.md" || true
  exit 1
fi

if [[ -e "${REPO_ROOT}/.ruler" || -L "${REPO_ROOT}/.ruler" ]]; then
  echo "error: temporary .ruler bridge exists in the real checkout" >&2
  exit 1
fi

echo "Ruler rule sync check passed."
