#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly SCRIPT_DIR
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
readonly REPO_ROOT
readonly SOURCE_DIR="${REPO_ROOT}/instructions/.ruler"

fixture_root="$(mktemp -d "${TMPDIR:-/tmp}/agent-hub-phase1.XXXXXX")"

cleanup() {
  rm -rf -- "${fixture_root}"
}

trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

mkdir -p -- "${fixture_root}/instructions" "${fixture_root}/scripts"
cp -R -- "${SOURCE_DIR}" "${fixture_root}/instructions/.ruler"
cp -- "${SCRIPT_DIR}/sync.sh" "${fixture_root}/scripts/sync.sh"
chmod +x "${fixture_root}/scripts/sync.sh"

apply_fixture() {
  "${fixture_root}/scripts/sync.sh" >/dev/null

  if [[ -e "${fixture_root}/.ruler" || -L "${fixture_root}/.ruler" ]]; then
    echo "error: fixture sync left its temporary .ruler bridge behind" >&2
    exit 1
  fi
}

normalize_outputs() {
  sed '1{/^<!-- Generated by Ruler -->$/d;}' \
    "${fixture_root}/CLAUDE.md" > "${fixture_root}/CLAUDE.normalized.md"
  sed '1{/^<!-- Generated by Ruler -->$/d;}' \
    "${fixture_root}/AGENTS.md" > "${fixture_root}/AGENTS.normalized.md"
}

rules_hash() {
  shasum -a 256 "${fixture_root}/CLAUDE.normalized.md" | awk '{print $1}'
}

generated_hashes() {
  shasum -a 256 \
    "${fixture_root}/CLAUDE.md" \
    "${fixture_root}/AGENTS.md" \
    "${fixture_root}/.gemini/settings.json"
}

# A Ruler parse failure after bridge creation must still clean the bridge.
printf '\n[invalid toml\n' >> "${fixture_root}/instructions/.ruler/ruler.toml"
if "${fixture_root}/scripts/sync.sh" >/dev/null 2>&1; then
  echo "error: invalid fixture configuration unexpectedly succeeded" >&2
  exit 1
fi
if [[ -e "${fixture_root}/.ruler" || -L "${fixture_root}/.ruler" ]]; then
  echo "error: failed fixture sync left its temporary .ruler bridge behind" >&2
  exit 1
fi
cp -- "${SOURCE_DIR}/ruler.toml" \
  "${fixture_root}/instructions/.ruler/ruler.toml"

# Scope-changing Ruler flags must be rejected by the wrapper.
if "${fixture_root}/scripts/sync.sh" --agents claude >/dev/null 2>&1; then
  echo "error: scope-changing sync option unexpectedly succeeded" >&2
  exit 1
fi

# A pre-existing bridge is user-visible state, so the wrapper must preserve and reject it.
ln -s -- "${fixture_root}/instructions/.ruler" "${fixture_root}/.ruler"
if "${fixture_root}/scripts/sync.sh" --dry-run >/dev/null 2>&1; then
  echo "error: pre-existing fixture bridge unexpectedly succeeded" >&2
  exit 1
fi
if [[ ! -L "${fixture_root}/.ruler" ]]; then
  echo "error: wrapper removed a pre-existing fixture bridge" >&2
  exit 1
fi
rm -- "${fixture_root}/.ruler"

# An interrupt while Ruler is running must return 130 and clean the bridge.
mkdir -p -- "${fixture_root}/fake-bin"
printf '%s\n' \
  '#!/usr/bin/env bash' \
  'kill -INT "${PPID}"' \
  'sleep 0.1' \
  'exit 0' > "${fixture_root}/fake-bin/npx"
chmod +x "${fixture_root}/fake-bin/npx"

signal_status=0
PATH="${fixture_root}/fake-bin:${PATH}" \
  "${fixture_root}/scripts/sync.sh" >/dev/null 2>&1 || signal_status=$?
if [[ "${signal_status}" -ne 130 ]]; then
  echo "error: interrupted fixture sync returned ${signal_status}, expected 130" >&2
  exit 1
fi
if [[ -e "${fixture_root}/.ruler" || -L "${fixture_root}/.ruler" ]]; then
  echo "error: interrupted fixture sync left its temporary .ruler bridge behind" >&2
  exit 1
fi

apply_fixture
normalize_outputs
cmp -s "${fixture_root}/CLAUDE.normalized.md" "${fixture_root}/AGENTS.normalized.md"
baseline_hash="$(rules_hash)"

# Reproduce accidental drift in one generated file, then prove sync repairs it.
printf '\nintentional generated-file drift\n' >> "${fixture_root}/CLAUDE.md"
normalize_outputs
if cmp -s "${fixture_root}/CLAUDE.normalized.md" "${fixture_root}/AGENTS.normalized.md"; then
  echo "error: drift fixture did not diverge" >&2
  exit 1
fi

# Dry-run may create a temporary bridge/cache entry, but must not alter outputs.
drift_hashes_before="$(generated_hashes)"
"${fixture_root}/scripts/sync.sh" --dry-run >/dev/null
drift_hashes_after="$(generated_hashes)"
if [[ "${drift_hashes_after}" != "${drift_hashes_before}" ]]; then
  echo "error: dry-run changed generated outputs" >&2
  exit 1
fi
if [[ -e "${fixture_root}/.ruler" || -L "${fixture_root}/.ruler" ]]; then
  echo "error: fixture dry-run left its temporary .ruler bridge behind" >&2
  exit 1
fi

apply_fixture
normalize_outputs
cmp -s "${fixture_root}/CLAUDE.normalized.md" "${fixture_root}/AGENTS.normalized.md"
if [[ "$(rules_hash)" != "${baseline_hash}" ]]; then
  echo "error: sync did not restore the canonical baseline" >&2
  exit 1
fi

# Change only the disposable canonical source and prove both outputs update.
printf '\n- Phase 1 propagation probe.\n' >> \
  "${fixture_root}/instructions/.ruler/20-workflow.md"
apply_fixture
normalize_outputs
cmp -s "${fixture_root}/CLAUDE.normalized.md" "${fixture_root}/AGENTS.normalized.md"
updated_hash="$(rules_hash)"
if [[ "${updated_hash}" == "${baseline_hash}" ]]; then
  echo "error: canonical source change did not reach generated outputs" >&2
  exit 1
fi
for output in CLAUDE.md AGENTS.md; do
  if ! grep -Fqx -- '- Phase 1 propagation probe.' "${fixture_root}/${output}"; then
    echo "error: propagation probe is missing from ${output}" >&2
    exit 1
  fi
done

# A second apply with no source changes must be idempotent.
apply_fixture
normalize_outputs
cmp -s "${fixture_root}/CLAUDE.normalized.md" "${fixture_root}/AGENTS.normalized.md"
if [[ "$(rules_hash)" != "${updated_hash}" ]]; then
  echo "error: repeated sync is not idempotent" >&2
  exit 1
fi

if [[ ! -f "${fixture_root}/.gemini/settings.json" ]]; then
  echo "error: Gemini CLI context configuration was not generated" >&2
  exit 1
fi
if ! node -e '
  const fs = require("fs");
  const config = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  if (config.contextFileName !== "AGENTS.md") process.exit(1);
' "${fixture_root}/.gemini/settings.json"; then
  echo "error: Gemini CLI context configuration is invalid" >&2
  exit 1
fi

for source_path in "${SOURCE_DIR}"/*.md; do
  source="$(basename -- "${source_path}")"
  for output in CLAUDE.md AGENTS.md; do
    if ! grep -Fq -- "<!-- Source: .ruler/${source} -->" "${fixture_root}/${output}"; then
      echo "error: ${source} is missing from ${output}" >&2
      exit 1
    fi
  done
done

echo "Phase 1 disposable-fixture acceptance passed."
